PUT http://localhost:5002/api/products/08db6d59-163e-41ae-84f3-4411bbeca367
Content-Type: application/json

{
  "no": "0976580419",
  "name": "Iphone 16 Pro Max",
  "summary": "Summary Iphone 16 Pro Max",
  "description": "Description Iphone 16 Pro Max",
  "price": 200000,
  "brandId": "08db6d53-36f1-49ad-86ff-d5cb9340c470",
  "categoryId": "08db6d53-36d6-46b0-82ad-91e7dc6f2562",
}
