//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catalog.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string account_number_max_length_50 {
            get {
                return ResourceManager.GetString("account_number_max_length_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string attribute_is_duplicate_key {
            get {
                return ResourceManager.GetString("attribute_is_duplicate_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string attribute_is_duplicate_value {
            get {
                return ResourceManager.GetString("attribute_is_duplicate_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string bank_address_max_length_255 {
            get {
                return ResourceManager.GetString("bank_address_max_length_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string bank_max_length_50 {
            get {
                return ResourceManager.GetString("bank_max_length_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string category_code_max_length_50 {
            get {
                return ResourceManager.GetString("category_code_max_length_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string category_code_required {
            get {
                return ResourceManager.GetString("category_code_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string category_image_max_length_255 {
            get {
                return ResourceManager.GetString("category_image_max_length_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string category_image_required {
            get {
                return ResourceManager.GetString("category_image_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string category_name_max_length_255 {
            get {
                return ResourceManager.GetString("category_name_max_length_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string category_name_required {
            get {
                return ResourceManager.GetString("category_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string category_order_number_must_be_greater_than_0 {
            get {
                return ResourceManager.GetString("category_order_number_must_be_greater_than_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string category_parent_id_is_invalid {
            get {
                return ResourceManager.GetString("category_parent_id_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string category_parent_invalid {
            get {
                return ResourceManager.GetString("category_parent_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string common_data_does_not_exist_or_was_deleted {
            get {
                return ResourceManager.GetString("common_data_does_not_exist_or_was_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string common_list_id_must_not_be_empty {
            get {
                return ResourceManager.GetString("common_list_id_must_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string common_payload_is_not_valid {
            get {
                return ResourceManager.GetString("common_payload_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string district_code_max_length_10 {
            get {
                return ResourceManager.GetString("district_code_max_length_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string fax_max_length_50 {
            get {
                return ResourceManager.GetString("fax_max_length_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_extension_is_not_valid {
            get {
                return ResourceManager.GetString("file_extension_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_is_required {
            get {
                return ResourceManager.GetString("file_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_must_be_smaller_than_4_MB {
            get {
                return ResourceManager.GetString("file_must_be_smaller_than_4_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string nation_code_max_length_10 {
            get {
                return ResourceManager.GetString("nation_code_max_length_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string province_code_max_length_10 {
            get {
                return ResourceManager.GetString("province_code_max_length_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_address_max_length_255 {
            get {
                return ResourceManager.GetString("supplier_address_max_length_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_address_required {
            get {
                return ResourceManager.GetString("supplier_address_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_code_max_length_50 {
            get {
                return ResourceManager.GetString("supplier_code_max_length_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_code_required {
            get {
                return ResourceManager.GetString("supplier_code_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_delegate_max_length_50 {
            get {
                return ResourceManager.GetString("supplier_delegate_max_length_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_delegate_required {
            get {
                return ResourceManager.GetString("supplier_delegate_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_does_not_exist_or_was_deleted {
            get {
                return ResourceManager.GetString("supplier_does_not_exist_or_was_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_id_is_invalid {
            get {
                return ResourceManager.GetString("supplier_id_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_ids_is_valid {
            get {
                return ResourceManager.GetString("supplier_ids_is_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_is_duplicate_email {
            get {
                return ResourceManager.GetString("supplier_is_duplicate_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_is_duplicate_name {
            get {
                return ResourceManager.GetString("supplier_is_duplicate_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_is_duplicate_phone {
            get {
                return ResourceManager.GetString("supplier_is_duplicate_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_name_max_length_255 {
            get {
                return ResourceManager.GetString("supplier_name_max_length_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string supplier_name_required {
            get {
                return ResourceManager.GetString("supplier_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_email_is_invalid {
            get {
                return ResourceManager.GetString("the_email_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_password_is_required {
            get {
                return ResourceManager.GetString("the_password_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_password_must_be_8_30_characters_long {
            get {
                return ResourceManager.GetString("the_password_must_be_8_30_characters_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_password_must_contains_at_least_1_lowercase_character__a_z_ {
            get {
                return ResourceManager.GetString("the_password_must_contains_at_least_1_lowercase_character_[a_z]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_password_must_contains_at_least_1_numeric__0_9_ {
            get {
                return ResourceManager.GetString("the_password_must_contains_at_least_1_numeric_[0_9]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_password_must_contains_at_least_1_special_character {
            get {
                return ResourceManager.GetString("the_password_must_contains_at_least_1_special_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_password_must_contains_at_least_1_uppercase_character__A_Z_ {
            get {
                return ResourceManager.GetString("the_password_must_contains_at_least_1_uppercase_character_[A_Z]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_phone_is_not_valid {
            get {
                return ResourceManager.GetString("the_phone_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_phone_is_required {
            get {
                return ResourceManager.GetString("the_phone_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_phone_must_be_10_characters_long {
            get {
                return ResourceManager.GetString("the_phone_must_be_10_characters_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string upload_image_failed {
            get {
                return ResourceManager.GetString("upload_image_failed", resourceCulture);
            }
        }
    }
}
