global using System.Net.Sockets;
global using System.Text;
global using System.Text.Json;
global using MessageBroker.Abstractions;
global using MessageBroker.Abstractions.Events;
global using Polly;
global using RabbitMQ.Client;
global using RabbitMQ.Client.Events;
global using RabbitMQ.Client.Exceptions;